apiVersion: v1
kind: Pod
metadata:
  generateName: test-nginx-pod-
  namespace: test-scheduler
  labels:
    app: test-nginx
spec:
  schedulerName: my-scheduler
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: Never
