apiVersion: v1
kind: Pod
metadata:
  generateName: test-basic-
  namespace: test-scheduler
  labels:
    app: test-basic
spec:
  schedulerName: my-scheduler
  restartPolicy: Never
  containers:
  - name: test-basic
    image: test-basic:latest   # aquí pones tu imagen local
    imagePullPolicy: Never
