apiVersion: v1
kind: Pod
metadata:
  name: test-nginx-pod
  namespace: test-scheduler
  labels:
    app: my-scheduler
spec:
  schedulerName: my-scheduler
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx:latest
