apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-scheduler
  labels:
    app: my-scheduler
spec:
  schedulerName: my-scheduler
  containers:
  - name: test-container
    image: busybox
    command: ["sleep", "3600"]
  restartPolicy: Never
