apiVersion: v1
kind: Pod
metadata:
  name: test-dev-pod
  namespace: test-scheduler
  labels:
    app: dev-app
    env: dev
spec:
  schedulerName: my-scheduler
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
