apiVersion: v1
kind: Pod
metadata:
  generateName: test-nginx-pod-
  namespace: test-scheduler
  labels:
    app: test-nginx
spec:
  schedulerName: my-scheduler
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: Never
    resources:
      requests:
        memory: "128Mi"
        cpu: "0.1"
      limits:
        memory: "256Mi"
        cpu: "0.25"
