apiVersion: v1
kind: Pod
metadata:
  generateName: test-basic-
  namespace: test-scheduler
  labels:
    app: test-basic
spec:
  schedulerName: my-scheduler
  restartPolicy: Never
  containers:
  - name: busy
    image: k8s.gcr.io/pause:3.9
    imagePullPolicy: Never
    resources:
      requests:
        memory: "64Mi"
        cpu: "0.05"
      limits:
        memory: "128Mi"
        cpu: "0.1"
